drop table if exists Account;
CREATE TABLE if not exists Account(
aid int(11) NOT NULL DEFAULT '0',
name varchar(60) default NULL comment '平台帐号',
domain varchar(10) default NULL comment '平台类型',
firstdate timestamp DEFAULT '0000-00-00 00:00:00' comment '首次登陆游戏的时间',
firstmac char(16) default null comment '首次登录mac地址',
firstsys tinyint(3) not null default '0' comment '首次登录平台，1,pc,2,andorid,3,ios',
lastdate timestamp DEFAULT '0000-00-00 00:00:00' comment '最后登陆游戏的时间',
lastmac char(16) default null comment '最后登录mac地址',
lastsys tinyint(3) not null default '0' comment '首次登录平台，1,pc,2,andorid,3,ios',
uid int(11) unsigned DEFAULT NULL comment '最高等级角色对应的角色id',
hostnum int(10) unsigned DEFAULT NULL comment '最高等级角色对应的服务器id',
nickname varchar(30) character set utf8 default null comment '角色名',
grade int(10) unsigned DEFAULT NULL comment '最高等级',
exp int(10) unsigned default null comment '经验值',
resid int(10) unsigned default null comment '职业',
vip int(10) unsigned default null comment '最高等级角色对应的vip等级',
questid int(10) unsigned default null comment '最高等级角色对应的主线任务',
PRIMARY KEY (domain,aid),
UNIQUE KEY name (name,domain),
UNIQUE KEY domain (domain,name),
KEY lastdate (lastdate),
KEY newdate (firstdate)
) ENGINE=InnoDB;

drop table if exists NewUser;
create table if not exists NewUser( 
aid int(10) not null default '0',
domain varchar(10) default NULL comment '平台类型',
uid int(11) unsigned DEFAULT NULL comment '最高等级角色对应的角色id',
grade int(10) unsigned DEFAULT NULL comment '最高等级',
resid int(10) unsigned default null comment '职业',
questid int(10) unsigned default null comment '最高等级角色对应的主线任务',
primary key(domain,aid));

drop table if exists FirstLogin;
create table if not exists FirstLogin(
day date not null,
new int(10) unsigned default '0' comment '新增',
warrier_m int(10) unsigned default '0' comment "男战士",
warrier_f int(10) unsigned default '0' comment "女战士",
archer_m int(10) unsigned default '0' comment "男弓手",
archer_f int(10) unsigned default '0' comment "女弓手",
master_m int(10) unsigned default '0' comment "女法师",
master_f int(10) unsigned default '0' comment "女法师",
guidence_0 int(10) unsigned default '0' comment "没有开始新手任务的角色数",
guidence_1 int(10) unsigned default '0' comment "新手任务",
guidence_2 int(10) unsigned default '0' comment "新手任务",
guidence_3 int(10) unsigned default '0' comment "新手任务",
guidence_4 int(10) unsigned default '0' comment "新手任务",
guidence_5 int(10) unsigned default '0' comment "新手任务",
guidence_6 int(10) unsigned default '0' comment "新手任务",
guidence_7 int(10) unsigned default '0' comment "新手任务",
guidence_8 int(10) unsigned default '0' comment "新手任务",
guidence_9 int(10) unsigned default '0' comment "新手任务",
guidence_10 int(10) unsigned default '0' comment "新手任务",
guidence_11 int(10) unsigned default '0' comment "新手任务",
guidence_12 int(10) unsigned default '0' comment "新手任务",
guidence_13 int(10) unsigned default '0' comment "新手任务",
guidence_14 int(10) unsigned default '0' comment "新手任务",
guidence_15 int(10) unsigned default '0' comment "新手任务",
guidence_16 int(10) unsigned default '0' comment "新手任务",
guidence_17 int(10) unsigned default '0' comment "新手任务",
guidence_18 int(10) unsigned default '0' comment "新手任务",
guidence_19 int(10) unsigned default '0' comment "新手任务",
guidence_20 int(10) unsigned default '0' comment "新手任务",
guidence_21 int(10) unsigned default '0' comment "新手任务",
guidence_22 int(10) unsigned default '0' comment "新手任务",
guidence_23 int(10) unsigned default '0' comment "新手任务",
guidence_24 int(10) unsigned default '0' comment "新手任务",
guidence_25 int(10) unsigned default '0' comment "新手任务",
guidence_26 int(10) unsigned default '0' comment "新手任务",
guidence_27 int(10) unsigned default '0' comment "新手任务",
guidence_finish int(10) unsigned default '0' comment "完成新手任务的角色数",
away_0 float(5,2) default '0' comment '新手引导流失率', 
away_1 float(5,2) default '0' comment '新手引导流失率', 
away_2 float(5,2) default '0' comment '新手引导流失率', 
away_3 float(5,2) default '0' comment '新手引导流失率', 
away_4 float(5,2) default '0' comment '新手引导流失率', 
away_5 float(5,2) default '0' comment '新手引导流失率', 
away_6 float(5,2) default '0' comment '新手引导流失率', 
away_7 float(5,2) default '0' comment '新手引导流失率', 
away_8 float(5,2) default '0' comment '新手引导流失率', 
away_9 float(5,2) default '0' comment '新手引导流失率', 
away_10 float(5,2) default '0' comment '新手引导流失率', 
away_11 float(5,2) default '0' comment '新手引导流失率', 
away_12 float(5,2) default '0' comment '新手引导流失率', 
away_13 float(5,2) default '0' comment '新手引导流失率', 
away_14 float(5,2) default '0' comment '新手引导流失率', 
away_15 float(5,2) default '0' comment '新手引导流失率', 
away_16 float(5,2) default '0' comment '新手引导流失率', 
away_17 float(5,2) default '0' comment '新手引导流失率', 
away_18 float(5,2) default '0' comment '新手引导流失率', 
away_19 float(5,2) default '0' comment '新手引导流失率', 
away_20 float(5,2) default '0' comment '新手引导流失率', 
away_21 float(5,2) default '0' comment '新手引导流失率', 
away_22 float(5,2) default '0' comment '新手引导流失率', 
away_23 float(5,2) default '0' comment '新手引导流失率', 
away_24 float(5,2) default '0' comment '新手引导流失率', 
away_25 float(5,2) default '0' comment '新手引导流失率', 
away_26 float(5,2) default '0' comment '新手引导流失率', 
away_27 float(5,2) default '0' comment '新手引导流失率', 
away_finish float(5,2) default '0' comment '新手引导流失率', 
primary key(day))engine=innodb comment '首次登陆相关统计';

drop table if exists Revenue;
create table if not exists Revenue(
day date not null,
arpu float(10,2) not null default '0' comment '每用户平均收入',
arppu float(10,2) not null default '0' comment '每付费用户平均收入',
pur float(5,2) not null default '0' comment '支付比',
apa int(10) unsigned default '0' comment '付费用户数',
dau int(10) unsigned default '0' comment '日活跃用户数',
revenue int(10) unsigned default '0' comment '总收入',
pay_count int(10) unsigned default '0' comment '支付次数',
vip0 int(10) unsigned default '0' comment 'vip0用户的人数',
vip1 int(10) unsigned default '0' comment 'vip1用户的人数',
vip2 int(10) unsigned default '0' comment 'vip2用户的人数',
vip3 int(10) unsigned default '0' comment 'vip3用户的人数',
vip4 int(10) unsigned default '0' comment 'vip4用户的人数',
vip5 int(10) unsigned default '0' comment 'vip5用户的人数',
vip6 int(10) unsigned default '0' comment 'vip6用户的人数',
vip7 int(10) unsigned default '0' comment 'vip7用户的人数',
vip8 int(10) unsigned default '0' comment 'vip8用户的人数',
vip9 int(10) unsigned default '0' comment 'vip9用户的人数',
vip10 int(10) unsigned default '0' comment 'vip10用户的人数',
vip11 int(10) unsigned default '0' comment 'vip11用户的人数',
vip12 int(10) unsigned default '0' comment 'vip12用户的人数',
primary key(day)) engine=innodb comment '付费相关统计';

drop table if exists Active;
create table if not exists Active(
day date not null,
dau int(10) unsigned default '0' comment '日活跃用户数',
new int(10) unsigned default '0' comment '新增用户数',
total int(10) unsigned default '0' comment '总用户数',
active_rate float(5,2) default '0' comment '活跃率', 
online float(5,2) default '0' comment '平均在线时长',
retention1_l float(5,2) default '0' comment '1日留存率', 
retention2_l float(5,2) default '0' comment '2日留存率', 
retention3_l float(5,2) default '0' comment '3日留存率', 
retention4_l float(5,2) default '0' comment '4日留存率', 
retention5_l float(5,2) default '0' comment '5日留存率', 
retention6_l float(5,2) default '0' comment '6日留存率', 
retention7_l float(5,2) default '0' comment '7日留存率', 
retention1_h float(5,2) default '0' comment '1日总留存率', 
retention2_h float(5,2) default '0' comment '2日总留存率', 
retention3_h float(5,2) default '0' comment '3日总留存率', 
retention4_h float(5,2) default '0' comment '4日总留存率', 
retention5_h float(5,2) default '0' comment '5日总留存率', 
retention6_h float(5,2) default '0' comment '6日总留存率', 
retention7_h float(5,2) default '0' comment '7日总留存率', 
primary key(day)) engine=innodb comment '活跃度相关统计';
